name: Python AI Model CI

on:
  push:
    branches: [ development, qa, production ]
    paths:
      - 'ai/**' # Assuming AI code is in an 'ai' directory
  pull_request:
    branches: [ development, qa, production ]
    paths:
      - 'ai/**'

jobs:
  test-ai-model:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ai/requirements.txt ]; then pip install -r ai/requirements.txt; fi

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 ai/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 ai/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Uncomment when you have tests
    # - name: Test with pytest
    #   run: |
    #     pip install pytest
    #     pytest ai/
