name: Python AI Model CI

on:
  push:
    paths:
      - 'ai/**'
  pull_request:
    paths:
      - 'ai/**'

jobs:
  test-ai-model:
    name: Test AI Model
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ai/requirements.txt ]; then pip install -r ai/requirements.txt; fi
          pip install pytest flake8
      
      - name: Lint with flake8
        run: |
          flake8 ai/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ai/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Test with pytest
        run: |
          if [ -d ai/tests ]; then pytest ai/tests; else echo "No tests found"; fi
      
      - name: Verify model loading
        run: |
          if [ -f ai/model/verify_model.py ]; then
            python ai/model/verify_model.py
          else
            echo "No model verification script found"
          fi
