name: React CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Polyfill Node Crypto
      run: |
        echo "export const getRandomValues = require('crypto').randomFillSync;" > crypto-polyfill.js
        echo "NODE_OPTIONS=--require ./crypto-polyfill.js" >> $GITHUB_ENV

    - name: Build
      run: npm run build

    # Add your deployment steps here
    # For example, deploying to GitHub Pages:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
