name: React CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Polyfill Node Crypto
      run: |
        echo "export const getRandomValues = require('crypto').randomFillSync;" > crypto-polyfill.js
        echo "NODE_OPTIONS=--require ./crypto-polyfill.js" >> $GITHUB_ENV
    
    - name: Build
      run: npm run build
    
    - name: Test
      run: npm test || echo "No tests specified"
