name: Production Deployment

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  react-build-test:
    name: React Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint || echo "Linting issues found"
      
      - name: Build
        run: npm run build
      
      - name: Test
        run: npm test || echo "Tests completed with issues"
      
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

  python-test:
    name: Python Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ai/requirements.txt ]; then pip install -r ai/requirements.txt; fi
          pip install pytest flake8
      
      - name: Lint with flake8
        run: |
          flake8 ai/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ai/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Test with pytest
        run: |
          if [ -d ai/tests ]; then pytest ai/tests; else echo "No tests found"; fi
      
      - name: Package AI model
        run: |
          mkdir -p ai-package
          cp -r ai/* ai-package/
          tar -czvf ai-model.tar.gz ai-package/
      
      - name: Archive AI model
        uses: actions/upload-artifact@v3
        with:
          name: ai-model-package
          path: ai-model.tar.gz

  deploy-production:
    name: Deploy to Production
    needs: [react-build-test, python-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist
      
      - name: Download AI model
        uses: actions/download-artifact@v3
        with:
          name: ai-model-package
          path: .
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
