name: Production Deployment

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  react-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./ # Adjust if your React code is in a subdirectory
      
      - name: Run linting
        run: npm run lint
        working-directory: ./ # Adjust if needed
      
      - name: Run tests
        run: npm test
        working-directory: ./ # Adjust if needed
      
      - name: Build
        run: npm run build
        working-directory: ./ # Adjust if needed

  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ai/requirements.txt ]; then pip install -r ai/requirements.txt; fi
          # Install test dependencies
          pip install pytest pytest-cov flake8
      
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ai --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 ai --count --exit-zero --max-complexity=10 --statistics
      
      - name: Test with pytest
        run: |
          if [ -d ai/tests ]; then
            pytest ai/tests --cov=ai
          else
            echo "No tests directory found, skipping tests"
            exit 0
          fi

  deploy-to-production:
    needs: [react-build-test, python-test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/production'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Adjust to your build output directory
          force_orphan: true
