# name: QA CI/CD

# on:
#   push:
#     branches: [ qa ]
#   pull_request:
#     branches: [ qa ]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3

#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18'
#         cache: 'npm'

#     - name: Install dependencies
#       run: npm ci

#     - name: Lint
#       run: npm run lint
      
#     # Uncomment when you have tests
#     # - name: Test
#     #   run: npm test
      
#     - name: Build
#       run: npm run build
      
#     # Optional: Deploy to QA environment
#     # For example, you could deploy to a separate GitHub Pages site or other hosting
#     # - name: Deploy to QA Environment
#     #   uses: peaceiris/actions-gh-pages@v3
#     #   with:
#     #     github_token: ${{ secrets.GITHUB_TOKEN }}
#     #     publish_dir: ./dist # Or your build output directory
#     #     destination_dir: qa # Create a subdirectory for QA deployments


name: QA CI/CD

on:
  push:
    branches: [ qa ]

jobs:
  react-build-test:
    # Same as in development-ci.yml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
      
    - name: Build
      run: npm run build

  python-test:
    # Same as in development-ci.yml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ai/requirements.txt ]; then pip install -r ai/requirements.txt; fi
        pip install pytest flake8
    
    - name: Lint with flake8
      run: |
        flake8 ai --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ai --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        if [ -d ai/tests ]; then pytest ai/tests; fi
        
  # Add deployment job if needed

